version: '3.8'

services:

  mongodb:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - dbdata6:/data/db
  parser:
    build:
      context: .
      dockerfile: "Dockerfile"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    container_name: parser
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  dbdata6: