version: '3.8'

services:

  mongodb:
    restart: always
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6: